[tox]
envlist = py313, check-manifest, check-typing

[testenv]
sitepackages = true
deps = .[test]
commands =
    python -m pytest \
        --basetemp={envtmpdir} \
        --cov=mopidy_listenbrainz --cov-report=term-missing \
        {posargs}

[testenv:check-manifest]
deps = .[lint]
commands = python -m check_manifest

[testenv:check-typing]
deps = .[typing]
commands = pyright mopidy_listenbrainz
